name: Build and Publish

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "*"
  release:
    types:
      - created

jobs:
  BuildNugetPackage:
    name: Build Nuget Package
    uses: ./.github/workflows/build-nuget-package.yml
    with:
      dotnet-version: 8.0.x
      configuration: Release

  ActionDisposableTests:
    name: ConfigurationCollection Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      dotnet-version: 8.0.x
      configuration: Release
      project-path: ./tests/ActionDisposableTests/src

  DisposableListTests:
    name: ConfigurationCollection Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      dotnet-version: 8.0.x
      configuration: Release
      project-path: ./tests/DisposableListTests/src

  DisposableObjectTests:
    name: ConfigurationCollection Tests
    needs: [BuildNugetPackage]
    uses: ./.github/workflows/execute-test.yml
    with:
      dotnet-version: 8.0.x
      configuration: Release
      project-path: ./tests/DisposableObjectTests/src

  BuildDocumentation:
    name: Build Documenation
    uses: ./.github/workflows/build-documentation.yml
    with:
      dotnet-version: 8.0.x

  PublishToGithub:
    name: Publish to Github
    needs: [ActionDisposableTests, DisposableListTests, DisposableObjectTests]
    uses: ./.github/workflows/publish-to-github.yml
    with:
      package-path: ./**/*.nupkg
    if: github.event_name == 'release' && github.event.action == 'created'
